# Generated by Django 3.1.4 on 2020-12-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('orgName', models.CharField(max_length=250)),
                ('slug', models.CharField(default='', max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
