# Generated by Django 3.1.4 on 2020-12-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201211_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document',
            field=models.FileField(default='', upload_to='resume'),
        ),
    ]
