# Generated by Django 3.1.4 on 2020-12-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201212_2014'),
        ('home', '0007_auto_20201212_2019'),
    ]

    operations = [
    ]
