# Generated by Django 3.1.4 on 2020-12-12 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='user',
            field=models.ManyToManyField(through='home.Enrollment', to=settings.AUTH_USER_MODEL),
        ),
    ]
