# Generated by Django 3.1.4 on 2020-12-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_merge_20201212_2021'),
        ('home', '0008_auto_20201212_2012'),
    ]

    operations = [
    ]
